providers = ['php', 'node']

[phases.setup]
nixPkgs = ['php84', 'php84Packages.composer', 'nodejs_22', 'ffmpeg']

[variables]
NIXPACKS_PHP_VERSION = '8.4'
NIXPACKS_NODE_VERSION = '22'
NIXPACKS_PHP_ROOT_DIR = '/app/public'
NIXPACKS_PHP_FALLBACK_PATH = '/index.php'
