<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('device_sessions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->onDelete('cascade');
            $table->string('device_id')->index(); // Unique persistent identifier generated by client
            $table->string('device_name')->nullable(); // e.g. "iPhone 15 Pro", "Chrome on macOS"
            $table->string('platform', 50)->nullable(); // ios, android, web, macos, windows
            $table->string('ip', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->unsignedBigInteger('personal_access_token_id')->nullable()->index();
            $table->boolean('is_trusted')->default(true);
            $table->timestamp('last_active_at')->useCurrent();
            $table->timestamp('revoked_at')->nullable();
            $table->timestamps();

            $table->index(['user_id', 'is_trusted', 'revoked_at']);
        });

        Schema::create('pending_login_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->onDelete('cascade');
            $table->string('request_token', 64)->unique();
            $table->string('device_id');
            $table->string('device_name')->nullable();
            $table->string('platform', 50)->nullable();
            $table->string('ip', 45)->nullable();
            $table->string('location', 100)->nullable();
            $table->string('status', 30)->default('pending'); // pending, approved, denied, expired, cancelled
            $table->timestamp('expires_at');
            $table->foreignId('approved_by_device_session_id')->nullable()->constrained('device_sessions')->nullOnDelete();
            $table->timestamp('approved_at')->nullable();
            $table->timestamp('denied_at')->nullable();
            $table->text('authorized_token')->nullable(); // Stored encrypted token once approved
            $table->timestamps();

            $table->index(['user_id', 'status', 'expires_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('pending_login_requests');
        Schema::dropIfExists('device_sessions');
    }
};

